table dim_canal
	lineageTag: 9f886125-6136-4d5d-abb6-fef6287c54de

	measure VentasCanal =
			CALCULATE(
			    COUNTROWS(Fact_Ventas),
			    CROSSFILTER(Fact_Ventas[Canal], dim_canal[id_canal], BOTH)
			)
		formatString: 0
		lineageTag: b81eb924-e18a-49ad-b6d1-8e0e48bec3e9

	column id_canal
		dataType: int64
		formatString: 0
		lineageTag: 3ece1ffc-190e-4532-96cb-8ea6168ad6ad
		summarizeBy: none
		sourceColumn: id_canal

		annotation SummarizationSetBy = Automatic

	column tipo_canal
		dataType: string
		lineageTag: 7b77b6dc-b68f-4a7d-afdc-e2d8d5ca79c5
		summarizeBy: none
		sourceColumn: tipo_canal

		annotation SummarizationSetBy = Automatic

	column canal
		dataType: string
		lineageTag: 3e329ce0-1fbf-4d98-851c-e42033855d8e
		summarizeBy: none
		sourceColumn: canal

		annotation SummarizationSetBy = Automatic

	partition dim_canal = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\isira\Downloads\VentasVehiculos.xlsx"), null, true),
				    dim_canal_Table = Origen{[Item="dim_canal",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(dim_canal_Table,{{"id_canal", Int64.Type}, {"tipo_canal", type text}, {"canal", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

