table Dim_Calendario
	lineageTag: 2e1dd35a-354d-408c-82ad-01a0f175166f

	measure TotalVentas = COUNTROWS(Fact_Ventas)
		formatString: 0
		lineageTag: e4a471e7-1851-4da5-a0d0-a34faba995bc

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 43b3d21a-3e91-4885-ab19-2d578143edeb
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: 88a6b2c7-4de3-41f5-8d0e-daaa31705353
			defaultHierarchy: LocalDateTable_7b0ba79a-7b3d-4628-9773-c4130eac74a8.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: ae95b4ea-e3e5-4ab0-9ce4-929cf6e4bb9d
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Semana
		dataType: int64
		formatString: 0
		lineageTag: 76dc7c36-e242-4721-9310-86d4c7525c00
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 71f6be62-e73e-4846-a080-54799a8b380e
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Numero Mes'
		dataType: int64
		formatString: 0
		lineageTag: b00c6014-58d5-41a6-b835-36fea71570a6
		summarizeBy: sum
		sourceColumn: Numero Mes

		annotation SummarizationSetBy = Automatic

	column datekey
		dataType: int64
		formatString: 0
		lineageTag: d4137791-3cbd-4ef9-ad4a-6fd2dd8b402a
		summarizeBy: none
		sourceColumn: datekey

		annotation SummarizationSetBy = Automatic

	partition Dim_Calendario = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\isira\Downloads\VentasVehiculos.xlsx"), null, true),
				    Dim_Calendario_Table = Origen{[Item="Dim_Calendario",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Dim_Calendario_Table,{{"Fecha", type date}, {"Año", Int64.Type}, {"Semana", Int64.Type}, {"Mes", type text}, {"Numero Mes", Int64.Type}, {"datekey", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

